image:
  repository: ruanbekker/blockchain-btc
  tag: 28.0
  digest: sha256:80824386f1b637d61ffb0d4b91c117d3b58687390f9088f6a029560889ba5e53
  pullPolicy: IfNotPresent

configuration:
  rpcuser: "user" # optional: if not quoted it will be generated
  txindex: 0
  server: 1
  network: testnet # required: (mainnet, regtest, signet or testnet) default: mainnet
  prune: 2
  disablewallet: 1
  passwordLength: 50 # this will be ignored if a passwordSecret is present
  # passwordSecret: "bitcoin-secrets" # use a existing secret and reference .password
  rpcallowip:
    - 0.0.0.0/0 
  rpcthreads: 16
  rpcworkqueue: 256
  rpcservertimeout: 60
  loglevel: info
  debug:
    - rpc
    - http
  logips: 1
  logsourcelocations: 1
  logthreadnames: 1

persistence:
  accessMode: ReadWriteOnce
  size: 20G
  storageClass: gp2

resources:
  requests:
    cpu: 250m
    memory: 1G
  limits:
    cpu: 1000m
    memory: 1G

monitoring:
  enabled: false
  exporterImage: "ruanbekker/f5ec-f4d6c675255536cc-fd46:metrics"
  exporterPort: 5000
  healthEndpoint: "/health"
  prometheusReleaseLabel: "prometheus"
  healthPollerImage: "appropriate/curl"
  healthEndpoint: "/health"
  healthPollInterval: 15
  server_type: "bitcoin"
  metrics_port: "5000"

affinity: {}
tolerations: []
podAnnotations: []

